# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-24 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20181024_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='thumps_up',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
